chore: add latest tagging task

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -9,3 +9,15 @@ tasks:
     desc: "pull new version of Meta Majin"
     cmds:
       - go get github.com/yasha-gh/meta-majin
+  tag:
+      desc: Create and push a new tag
+      cmds:
+        - |
+          if git diff-index --quiet HEAD --; then
+            git fetch origin master
+            git tag -a "latest" -m "latest"
+            git push origin tag "latest"
+          else
+            echo "Error: There are uncommitted changes. Please commit or stash your changes before creating a new tag."
+            exit 1
+          fi
